all:
	export WANT_AUTOMAKE=1.7
	echo "running libtoolize..."
	libtoolize --copy --force --automake
	echo "running aclocal..."
	aclocal
	echo "running autoconf..."
	autoconf
	echo "running automake..."
	automake --include-deps --add-missing --copy
	echo
	echo You are now ready to run ./configure
	echo enjoy!

.SILENT:
