.TH BBKEYSRC 5 "January 12, 2002" bbtools bbkeysrc
.SH NAME
bbkeysrc \- bbkeys keymap configuration file

.SH SYNOPSIS
.B $HOME/.bbkeysrc

.SH DESCRIPTION

\fBbbkeys\fR picks up its style-settings from the same places as the other
bbtools (such as \fIbbmail(1)\fR).  In most cases, this will be
\fI$HOME/.blackboxrc\fR. But its key-grabbings come from $HOME/.bbkeysrc.
There are several avenues open to the user to set any key-grabs that the user
wishes:

.SS "Using \fIbbconf\fR:"
This is a Qt-based application available at http://bbconf.sourceforge.net/.

.SS "Using \fIbbkeysconf\fR:"
This is a Qt-based application previously distributed with bbkeys. It has 
been superceded by \fIbbconf\fR, and no further development goes into it.

.SS "Without \fIbbkeysconf\fR:"
\fBbbkeys\fR can be launched with the \fI-noqt\fR option and whenever the
little reconfigure button (the key-hole) on \fBbbkeys\fR is clicked,
\fBbbkeys\fR will launch a very simple interactive rc-file generator, called
bbkeysconf.pl (written in perl) inside of an xterm.  If you choose not to
use the QT bbconf application, bbkeysconf.pl is the recommended way of
editting your keybinding rc-file.

.SS "Manually editing \fI$HOME/.bbkeysrc\fR:"
The format is very easy, and it consists of lines describing the Key to grab,
the modifier to grab the key with (if any, or "None" if none), and the action
to perform. For example:

KeyToGrab(Tab), WithModifier(Mod1), WithAction(NextWindow)
.br
KeyToGrab(t), WithModifier(Mod1), WithAction(ExecCommand),
                                           DoThis(xterm)

.SH "List of commands"

BigNudgeDown
.br
BigNudgeLeft
.br
BigNudgeRight
.br
BigNudgeUp
.br
Close
.br
ExecCommand
.br
HorizontalDecrement
.br
HorizontalIncrement
.br
Lower
.br
MaximizeHorizontal
.br
MaximizeVertical
.br
MaximizeWindow
.br
Minimize
.br
NextWindow
.br
NextWindowAllWorkspaces
.br
NextWorkspace
.br
NudgeDown
.br
NudgeLeft
.br
NudgeUp
.br
NudgeRight
.br
PrevWindow
.br
PrevWorkspace
.br
Raise
.br
ShadeWindow
.br
StickWindow
.br
ToggleDecor
.br
Workspace1
.br
Workspace2
.br
Workspace3
.br
Workspace4
.br
Workspace5
.br
Workspace6
.br
Workspace7
.br
Workspace8
.br
Workspace9
.br
Workspace10
.br
Workspace11
.br
Workspace12
.br
VerticalIncrement
.br
VerticalDecrement


.SH "SEE ALSO"
.BR bbkeys(1),
.BR bbkeys.bb(5)

.SH AUTHOR
.nr
Jason 'vanRijn' Kasper <vR@movingparts.net> - bbkeys
.br
Jan Schaumann <jschauma@netmeister.org> - this man page
